#!/bin/bash
# Integration tests for Rivet's HTML export.
#
# Verifies multi-page and single-page export correctness:
#   - All expected files are generated
#   - No absolute URLs (all links are relative)
#   - Navigation bar present on every page
#   - Footer with version present on every page
#   - Anchor links within pages resolve to existing ids
#   - Cross-page links reference valid files and anchors
#   - Single-page mode produces one index.html with all sections
#   - Pages are self-contained (embedded CSS, no external deps)
#
# Usage:
#   bash tests/playwright-export.sh
#
# Requires: cargo, python3

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
export EXPORT_DIR=$(mktemp -d)
export SINGLE_DIR=$(mktemp -d)
PASS=0
FAIL=0

cleanup() {
  rm -rf "$EXPORT_DIR" "$SINGLE_DIR"
}
trap cleanup EXIT

pass() {
  printf "  \033[32mPASS\033[0m  %s\n" "$1"
  PASS=$((PASS + 1))
}

fail() {
  printf "  \033[31mFAIL\033[0m  %s\n" "$1"
  FAIL=$((FAIL + 1))
}

# ── Build and generate multi-page export ────────────────────────────────

echo "==> Building rivet and generating multi-page HTML export..."
(cd "$SCRIPT_DIR" && cargo run --quiet -- export --format html --output "$EXPORT_DIR" 2>&1)

echo ""
echo "── Multi-page export checks ──"

# ── 1. Verify core pages exist ──────────────────────────────────────────

CORE_PAGES="index.html requirements.html documents.html matrix.html coverage.html validation.html"
for f in $CORE_PAGES; do
  if [ -f "$EXPORT_DIR/$f" ]; then
    pass "$f exists"
  else
    fail "$f missing"
  fi
done

# ── 2. No absolute URLs in href attributes ─────────────────────────────

for f in "$EXPORT_DIR"/*.html; do
  base=$(basename "$f")
  if grep -qE 'href="https?://' "$f" 2>/dev/null; then
    fail "$base contains absolute href URL"
    grep -oE 'href="https?://[^"]*"' "$f" | head -3 | while read -r line; do
      printf "         %s\n" "$line"
    done
  else
    pass "$base has only relative hrefs"
  fi
done

# ── 3. No localhost references ─────────────────────────────────────────

for f in "$EXPORT_DIR"/*.html; do
  base=$(basename "$f")
  if grep -qi 'localhost' "$f" 2>/dev/null; then
    fail "$base references localhost"
  else
    pass "$base has no localhost references"
  fi
done

# ── 4. Navigation bar present on every page ────────────────────────────

for f in "$EXPORT_DIR"/*.html; do
  base=$(basename "$f")
  if grep -q '<nav' "$f"; then
    pass "$base has navigation bar"
  else
    fail "$base missing navigation bar"
  fi
done

# ── 5. Nav references all core pages ──────────────────────────────────

for f in "$EXPORT_DIR"/*.html; do
  base=$(basename "$f")
  all_found=true
  for label in Overview Requirements Documents Matrix Coverage Validation; do
    if ! grep -q "$label" "$f"; then
      fail "$base nav missing label '$label'"
      all_found=false
    fi
  done
  if $all_found; then
    pass "$base nav references all core pages"
  fi
done

# ── 6. Footer with version present on every page ──────────────────────

for f in "$EXPORT_DIR"/*.html; do
  base=$(basename "$f")
  if grep -q '<footer' "$f"; then
    if grep -q 'Generated by Rivet' "$f"; then
      pass "$base has footer with version"
    else
      fail "$base has footer but missing version text"
    fi
  else
    fail "$base missing footer"
  fi
done

# ── 7. Valid HTML document structure ──────────────────────────────────

for f in "$EXPORT_DIR"/*.html; do
  base=$(basename "$f")
  if grep -q '<!DOCTYPE html>' "$f" && grep -q '<html' "$f" && grep -q '</html>' "$f"; then
    pass "$base has valid HTML document structure"
  else
    fail "$base missing HTML document structure"
  fi
done

# ── 8. Main content area present ──────────────────────────────────────

for f in "$EXPORT_DIR"/*.html; do
  base=$(basename "$f")
  if grep -q '<main>' "$f"; then
    pass "$base has <main> content area"
  else
    fail "$base missing <main> content area"
  fi
done

# ── 9. CSS is embedded (self-contained, no external stylesheets) ─────

for f in "$EXPORT_DIR"/*.html; do
  base=$(basename "$f")
  if grep -q '<style>' "$f"; then
    pass "$base has embedded CSS"
  else
    fail "$base missing embedded CSS"
  fi
  if grep -qE '<link[^>]+stylesheet' "$f" 2>/dev/null; then
    fail "$base has external stylesheet link"
  else
    pass "$base has no external stylesheet dependencies"
  fi
done

# ── 10. Anchor link integrity and cross-page link validation ──────────

echo ""
echo "── Anchor link integrity ──"

python3 << 'PYEOF'
import re, sys, os, glob as gl

export_dir = os.environ["EXPORT_DIR"]

# --- requirements.html internal anchors ---
req_path = os.path.join(export_dir, "requirements.html")
if os.path.exists(req_path):
    with open(req_path) as f:
        html = f.read()
    hrefs = re.findall(r'href="#([^"]+)"', html)
    ids = re.findall(r'id="([^"]+)"', html)
    id_set = set(ids)
    broken = [h for h in hrefs if h not in id_set]
    if broken:
        print(f"  \033[31mFAIL\033[0m  requirements.html: {len(broken)} broken anchors: {broken[:5]}")
        sys.exit(1)
    print(f"  \033[32mPASS\033[0m  requirements.html: {len(hrefs)} anchor links all resolve ({len(ids)} ids)")
else:
    print("  \033[31mFAIL\033[0m  requirements.html not found")
    sys.exit(1)

# --- Cross-page link file existence ---
html_files = gl.glob(os.path.join(export_dir, "*.html"))
file_basenames = {os.path.basename(f) for f in html_files}

errors = []
for fpath in html_files:
    base = os.path.basename(fpath)
    with open(fpath) as f:
        html = f.read()
    # Match href="./somefile.html" or href="somefile.html"
    refs = re.findall(r'href="(?:\./)?([^"#]+\.html)(?:#[^"]*)?\"', html)
    for ref in refs:
        if ref not in file_basenames:
            errors.append(f"{base} links to non-existent {ref}")

if errors:
    for e in errors[:10]:
        print(f"  \033[31mFAIL\033[0m  {e}")
    sys.exit(1)
print(f"  \033[32mPASS\033[0m  All cross-page file links reference existing files ({len(file_basenames)} pages)")

# --- Cross-page anchor links resolve ---
file_ids = {}
for fpath in html_files:
    base = os.path.basename(fpath)
    with open(fpath) as f:
        html = f.read()
    ids = set(re.findall(r'id="([^"]+)"', html))
    file_ids[base] = ids

errors = []
for fpath in html_files:
    base = os.path.basename(fpath)
    with open(fpath) as f:
        html = f.read()
    # Match href="./somefile.html#anchor" or href="somefile.html#anchor"
    refs = re.findall(r'href="(?:\./)?([^"#]+\.html)#([^"]+)"', html)
    for target_file, anchor in refs:
        if target_file in file_ids:
            if anchor not in file_ids[target_file]:
                errors.append(f"{base} -> {target_file}#{anchor}")

if errors:
    for e in errors[:10]:
        print(f"  \033[31mFAIL\033[0m  Broken cross-page anchor: {e}")
    sys.exit(1)
print(f"  \033[32mPASS\033[0m  All cross-page anchor links resolve")
PYEOF
PASS=$((PASS + 3))

# ── 11. No external JavaScript dependencies ──────────────────────────

echo ""
echo "── Self-containment checks ──"

for f in "$EXPORT_DIR"/*.html; do
  base=$(basename "$f")
  if grep -qE '<script[^>]+src=' "$f" 2>/dev/null; then
    fail "$base has external script dependency"
  else
    pass "$base has no external script dependencies"
  fi
done

# ── Single-page export ────────────────────────────────────────────────

echo ""
echo "==> Generating single-page HTML export..."
(cd "$SCRIPT_DIR" && cargo run --quiet -- export --format html --single-page --output "$SINGLE_DIR" 2>&1)

echo ""
echo "── Single-page export checks ──"

# ── 12. Single-page index.html exists ─────────────────────────────────

if [ -f "$SINGLE_DIR/index.html" ]; then
  pass "single-page index.html exists"
else
  fail "single-page index.html missing"
fi

# ── 13. Only one HTML file in single-page mode ───────────────────────

HTML_COUNT=$(find "$SINGLE_DIR" -name '*.html' | wc -l | tr -d ' ')
if [ "$HTML_COUNT" -eq 1 ]; then
  pass "single-page mode produced exactly 1 HTML file"
else
  fail "single-page mode produced $HTML_COUNT HTML files (expected 1)"
fi

# ── 14. Single page has all required section ids ─────────────────────

for section in index requirements documents matrix coverage validation; do
  if grep -q "id=\"$section\"" "$SINGLE_DIR/index.html"; then
    pass "single-page has section #$section"
  else
    fail "single-page missing section #$section"
  fi
done

# ── 15. Single-page nav uses fragment anchors ─────────────────────────

if grep -q 'href="#requirements"' "$SINGLE_DIR/index.html"; then
  pass "single-page nav uses fragment anchors"
else
  fail "single-page nav does not use fragment anchors"
fi

# ── 16. Single-page has footer ────────────────────────────────────────

if grep -q '<footer' "$SINGLE_DIR/index.html" && \
   grep -q 'Generated by Rivet' "$SINGLE_DIR/index.html"; then
  pass "single-page has footer with version"
else
  fail "single-page missing footer or version"
fi

# ── 17. Single-page has nav ──────────────────────────────────────────

if grep -q '<nav' "$SINGLE_DIR/index.html"; then
  pass "single-page has navigation bar"
else
  fail "single-page missing navigation bar"
fi

# ── 18. Single-page has embedded CSS ─────────────────────────────────

if grep -q '<style>' "$SINGLE_DIR/index.html"; then
  pass "single-page has embedded CSS"
else
  fail "single-page missing embedded CSS"
fi

# ── 19. Single-page has valid HTML structure ─────────────────────────

if grep -q '<!DOCTYPE html>' "$SINGLE_DIR/index.html" && \
   grep -q '</html>' "$SINGLE_DIR/index.html"; then
  pass "single-page has valid HTML document structure"
else
  fail "single-page missing HTML document structure"
fi

# ── 20. Single-page internal anchor links resolve ────────────────────

python3 << 'PYEOF2'
import re, sys, os

path = os.path.join(os.environ["SINGLE_DIR"], "index.html")
if not os.path.exists(path):
    print("  \033[31mFAIL\033[0m  single-page index.html not found")
    sys.exit(1)

with open(path) as f:
    html = f.read()

hrefs = re.findall(r'href="#([^"]+)"', html)
ids = set(re.findall(r'id="([^"]+)"', html))
broken = [h for h in hrefs if h not in ids]
if broken:
    print(f"  \033[31mFAIL\033[0m  single-page: {len(broken)} broken anchor links: {broken[:5]}")
    sys.exit(1)
print(f"  \033[32mPASS\033[0m  single-page: {len(hrefs)} anchor links all resolve ({len(ids)} ids)")
PYEOF2
PASS=$((PASS + 1))

# ── 21. No external JS in single-page ────────────────────────────────

if grep -qE '<script[^>]+src=' "$SINGLE_DIR/index.html" 2>/dev/null; then
  fail "single-page has external script dependency"
else
  pass "single-page has no external script dependencies"
fi

# ── Summary ───────────────────────────────────────────────────────────

echo ""
echo "════════════════════════════════════════════════"
printf "  Results:  \033[32m%d passed\033[0m" "$PASS"
if [ "$FAIL" -gt 0 ]; then
  printf ",  \033[31m%d failed\033[0m" "$FAIL"
fi
echo ""
echo "════════════════════════════════════════════════"

if [ "$FAIL" -gt 0 ]; then
  exit 1
fi
echo ""
echo "All HTML export tests passed!"
