//! Managed-section markers for files that `rivet init --agents` regenerates.
//!
//! Background: previously `rivet init --agents` unconditionally overwrote
//! `AGENTS.md`, destroying any manual content users (or downstream projects
//! like sigil) had added. Downstream projects worked around this by placing
//! load-bearing warning comments at the top of the file saying "don't
//! regenerate or you'll lose the manual audit section".
//!
//! This module provides a marker-based splice scheme so regeneration and
//! hand-edits can coexist: only the content between `BEGIN rivet-managed`
//! and `END rivet-managed` is replaced; anything outside is preserved.
//!
//! The markers are HTML comments, which are valid in Markdown and invisible
//! in rendered output:
//!
//! ```markdown
//! <!-- BEGIN rivet-managed: auto-generated section. Edits between these
//!      markers will be overwritten on `rivet init --agents`. -->
//! ... generated content ...
//! <!-- END rivet-managed -->
//! ```
//!
//! Semantics (see `splice_managed_section`):
//! - File has exactly one marker pair: replace the region between them.
//! - File has zero markers: return `NoMarkers` error (caller decides what
//!   to do — default is refuse, `--migrate` wraps existing content,
//!   `--force-regen` overwrites).
//! - File has multiple marker pairs: return `MultipleMarkers` error listing
//!   the line numbers.

use thiserror::Error;

/// Marker line that opens a managed region.
///
/// Matched by prefix so the trailing explanatory text can be updated without
/// breaking detection of already-markered files.
pub const BEGIN_MARKER_PREFIX: &str = "<!-- BEGIN rivet-managed";

/// Marker line that closes a managed region.
pub const END_MARKER_PREFIX: &str = "<!-- END rivet-managed";

/// Full text of the opening marker written for fresh files.
pub const BEGIN_MARKER: &str = "<!-- BEGIN rivet-managed: auto-generated section. Edits between these markers will be overwritten on `rivet init --agents`. -->";

/// Full text of the closing marker written for fresh files.
pub const END_MARKER: &str = "<!-- END rivet-managed -->";

/// Sentinel note embedded at the top of the managed region so the content
/// itself reminds readers that the region regenerates.
pub const MANAGED_SENTINEL: &str = "> NOTE: This section is auto-generated by `rivet init --agents`. Do not edit between the `BEGIN rivet-managed` / `END rivet-managed` markers — edits there are overwritten on regeneration. Content outside the markers is preserved.";

/// Errors returned by [`splice_managed_section`].
#[derive(Debug, Error, PartialEq, Eq)]
pub enum ManagedSectionError {
    /// The existing file has no `BEGIN rivet-managed` marker. The caller
    /// must decide whether to refuse (default), wrap (`--migrate`), or
    /// overwrite (`--force-regen`).
    #[error("file has no rivet-managed markers")]
    NoMarkers,

    /// The existing file has more than one `BEGIN`/`END` pair. We refuse
    /// rather than pick one, because doing so could silently destroy
    /// content the user meant to preserve.
    ///
    /// The `Vec<usize>` contains 1-based line numbers of every `BEGIN`
    /// line we found, so the caller can report them.
    #[error("file has multiple rivet-managed BEGIN markers at lines {0:?}")]
    MultipleBeginMarkers(Vec<usize>),

    /// A `BEGIN` marker was found with no matching `END` marker after it.
    #[error("rivet-managed BEGIN marker at line {begin_line} has no matching END marker")]
    UnclosedMarker { begin_line: usize },

    /// An `END` marker appears before any `BEGIN` marker.
    #[error("rivet-managed END marker at line {end_line} appears before any BEGIN marker")]
    OrphanEndMarker { end_line: usize },
}

/// Locate the single `BEGIN`/`END` marker pair in `existing`.
///
/// Returns `(begin_byte_start, end_byte_end_exclusive)` on success — i.e.
/// the byte range covering both marker lines inclusive, so the caller can
/// replace it with `begin_marker + new_managed + end_marker`.
fn find_marker_pair(existing: &str) -> Result<(usize, usize), ManagedSectionError> {
    // Collect all BEGIN and END lines with their byte offsets and line numbers.
    let mut begins: Vec<(usize, usize)> = Vec::new(); // (byte_offset_of_line_start, line_number)
    let mut ends: Vec<(usize, usize, usize)> = Vec::new(); // (byte_offset_of_line_start, byte_offset_after_line, line_number)

    let mut cursor: usize = 0;
    for (line_idx, line) in existing.split_inclusive('\n').enumerate() {
        let line_no = line_idx + 1;
        let trimmed = line.trim_start();
        if trimmed.starts_with(BEGIN_MARKER_PREFIX) {
            begins.push((cursor, line_no));
        } else if trimmed.starts_with(END_MARKER_PREFIX) {
            ends.push((cursor, cursor + line.len(), line_no));
        }
        cursor += line.len();
    }

    if begins.is_empty() && ends.is_empty() {
        return Err(ManagedSectionError::NoMarkers);
    }

    if begins.len() > 1 {
        let line_nos = begins.iter().map(|(_, n)| *n).collect();
        return Err(ManagedSectionError::MultipleBeginMarkers(line_nos));
    }

    // Exactly one BEGIN (or zero BEGIN + some END which is also invalid).
    let (begin_offset, begin_line_no) = match begins.first() {
        Some(&b) => b,
        None => {
            // Only orphan ENDs — surface the first one.
            let (_, _, end_line) = ends[0];
            return Err(ManagedSectionError::OrphanEndMarker { end_line });
        }
    };

    // Find the first END after the BEGIN.
    let matching_end = ends
        .iter()
        .find(|(offset, _, _)| *offset > begin_offset)
        .copied();

    match matching_end {
        Some((_, end_after, _)) => Ok((begin_offset, end_after)),
        None => Err(ManagedSectionError::UnclosedMarker {
            begin_line: begin_line_no,
        }),
    }
}

/// Replace the managed section of `existing` with `new_managed`, preserving
/// everything outside the markers byte-for-byte.
///
/// `new_managed` is the body content *between* the markers; it will be
/// wrapped by the canonical `BEGIN_MARKER` / `END_MARKER` lines so that
/// subsequent calls continue to find the markers even if the existing ones
/// had slightly different comment text.
///
/// Errors:
/// - [`ManagedSectionError::NoMarkers`] if `existing` has no BEGIN marker.
/// - [`ManagedSectionError::MultipleBeginMarkers`] if there is more than
///   one BEGIN marker.
/// - [`ManagedSectionError::UnclosedMarker`] if a BEGIN has no matching END.
/// - [`ManagedSectionError::OrphanEndMarker`] if an END appears before any
///   BEGIN.
pub fn splice_managed_section(
    existing: &str,
    new_managed: &str,
) -> Result<String, ManagedSectionError> {
    let (begin, end) = find_marker_pair(existing)?;

    let before = &existing[..begin];
    let after = &existing[end..];

    let mut out = String::with_capacity(before.len() + new_managed.len() + after.len() + 256);
    out.push_str(before);
    out.push_str(BEGIN_MARKER);
    out.push('\n');
    out.push_str(new_managed);
    // Guarantee the END marker starts on its own line.
    if !new_managed.ends_with('\n') {
        out.push('\n');
    }
    out.push_str(END_MARKER);
    out.push('\n');
    // Re-attach trailing content. `end` already points past the `\n` of the
    // END marker line in the original, so `after` starts at the next line.
    out.push_str(after);
    Ok(out)
}

/// Wrap `managed_body` with a BEGIN/END marker block suitable for a fresh
/// file (no existing content). The caller may prepend an editorial preamble
/// before this string.
pub fn wrap_fresh(managed_body: &str) -> String {
    let mut out = String::with_capacity(managed_body.len() + 256);
    out.push_str(BEGIN_MARKER);
    out.push('\n');
    out.push_str(managed_body);
    if !managed_body.ends_with('\n') {
        out.push('\n');
    }
    out.push_str(END_MARKER);
    out.push('\n');
    out
}

/// Produce a file for `--migrate`: the managed section on top, a short
/// separator, then all of the existing content preserved verbatim below.
pub fn migrate_wrap(existing: &str, managed_body: &str) -> String {
    let mut out = wrap_fresh(managed_body);
    out.push('\n');
    out.push_str("<!-- The content below was present before `rivet init --agents --migrate` wrapped this file. It is preserved verbatim; rivet will not touch it on subsequent regenerations. -->\n\n");
    out.push_str(existing);
    if !existing.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Quick predicate: does `existing` look like it already has managed
/// markers? Useful for callers that only need a yes/no answer and don't
/// want to materialize a `ManagedSectionError`.
pub fn has_markers(existing: &str) -> bool {
    existing
        .lines()
        .any(|l| l.trim_start().starts_with(BEGIN_MARKER_PREFIX))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn splice_replaces_only_managed_region() {
        let existing = "\
# Header

Manual prose above.

<!-- BEGIN rivet-managed: old -->
old generated body
<!-- END rivet-managed -->

Manual prose below.
";
        let out = splice_managed_section(existing, "new body\nmore\n").unwrap();
        assert!(out.contains("Manual prose above."));
        assert!(out.contains("Manual prose below."));
        assert!(out.contains("new body"));
        assert!(!out.contains("old generated body"));
        // BEGIN marker is normalized to canonical form.
        assert!(out.contains(BEGIN_MARKER));
        assert!(out.contains(END_MARKER));
    }

    #[test]
    fn splice_no_markers_returns_error() {
        let existing = "# Just prose\nNothing here.\n";
        let err = splice_managed_section(existing, "x").unwrap_err();
        assert_eq!(err, ManagedSectionError::NoMarkers);
    }

    #[test]
    fn splice_multiple_begin_markers_returns_error() {
        let existing = "\
<!-- BEGIN rivet-managed -->
a
<!-- END rivet-managed -->
middle
<!-- BEGIN rivet-managed -->
b
<!-- END rivet-managed -->
";
        let err = splice_managed_section(existing, "x").unwrap_err();
        match err {
            ManagedSectionError::MultipleBeginMarkers(lines) => {
                assert_eq!(lines, vec![1, 5]);
            }
            other => panic!("expected MultipleBeginMarkers, got {other:?}"),
        }
    }

    #[test]
    fn splice_unclosed_marker_returns_error() {
        let existing = "before\n<!-- BEGIN rivet-managed -->\nno end marker\n";
        let err = splice_managed_section(existing, "x").unwrap_err();
        assert_eq!(err, ManagedSectionError::UnclosedMarker { begin_line: 2 });
    }

    #[test]
    fn splice_orphan_end_marker_returns_error() {
        let existing = "before\n<!-- END rivet-managed -->\nafter\n";
        let err = splice_managed_section(existing, "x").unwrap_err();
        assert_eq!(err, ManagedSectionError::OrphanEndMarker { end_line: 2 });
    }

    #[test]
    fn splice_preserves_trailing_content_exactly() {
        let existing = "\
<!-- BEGIN rivet-managed -->
x
<!-- END rivet-managed -->
trailer line
";
        let out = splice_managed_section(existing, "y").unwrap();
        assert!(out.ends_with("trailer line\n"), "got:\n{out}");
    }

    #[test]
    fn wrap_fresh_produces_valid_markered_file() {
        let out = wrap_fresh("hello\nworld\n");
        assert!(out.starts_with(BEGIN_MARKER));
        assert!(out.contains("hello\nworld\n"));
        assert!(out.trim_end().ends_with(END_MARKER));
        // Round-trip through splice.
        let replaced = splice_managed_section(&out, "replaced\n").unwrap();
        assert!(replaced.contains("replaced\n"));
        assert!(!replaced.contains("hello"));
    }

    #[test]
    fn migrate_wrap_keeps_original_below_managed_region() {
        let existing = "# Downstream manual content\nline 2\n";
        let out = migrate_wrap(existing, "gen body\n");
        assert!(out.starts_with(BEGIN_MARKER));
        let (managed, below) = out.split_once(END_MARKER).expect("END marker must appear");
        assert!(managed.contains("gen body"));
        assert!(below.contains("# Downstream manual content"));
        assert!(below.contains("line 2"));
        assert!(has_markers(&out));
    }

    #[test]
    fn has_markers_true_for_markered_file() {
        assert!(has_markers(
            "<!-- BEGIN rivet-managed: something -->\nx\n<!-- END rivet-managed -->\n"
        ));
    }

    #[test]
    fn has_markers_false_for_plain_file() {
        assert!(!has_markers("# Hello\n\nJust prose.\n"));
    }

    #[test]
    fn splice_handles_missing_trailing_newline_in_new_content() {
        let existing = "<!-- BEGIN rivet-managed -->\nold\n<!-- END rivet-managed -->\n";
        let out = splice_managed_section(existing, "no-newline").unwrap();
        assert!(out.contains("no-newline\n<!-- END rivet-managed -->"));
    }
}
